#!/bin/bash

commands=(
    "ros2 action send_goal /gary/leds/leds_play_animation gary_leds_msgs/action/LedsPlayAnimation '{group: "head", color: "red", repetitions: 2, speed: 1,execution_control: 0,animation: "wave"}' --feedback"
    "ros2 action send_goal /gary/leds/leds_play_animation gary_leds_msgs/action/LedsPlayAnimation '{group: "head", color: "green", repetitions: 2, speed: 1,execution_control: 0,animation: "wave"}' --feedback"
    "ros2 action send_goal /gary/leds/leds_play_animation gary_leds_msgs/action/LedsPlayAnimation '{group: "head", color: "blue", repetitions: 2, speed: 1,execution_control: 0,animation: "wave"}' --feedback"
)

# Number of commands
total_commands=${#commands[@]}

# Select random command
random_index=$((RANDOM % total_commands))
selected_command=${commands[$random_index]}

# Execute
echo "Executing: $selected_command"
eval $selected_command
