/**:
  ros__parameters:

    groups:
      - head
      - chest

    head:
      id: 72
      can_id: 0x103
      recognizer: 0x48
      animation:
        - OFF.0x00
        - ON.0x01
        - ARROW_DOWN.0x02
        - WAVE.0x03
        - SIDE_2_SIDE.0x04
        - TALKING.0x05
        - THINKING.0x06
        - ARROW_DOWN_LEFT.0x07
        - BREATHING_LINE.0x08
        - IDLE_LINE.0x09
        - TALKING_IN.0x0A
        - TALKING_OUT.0x0B
        - ARROW_DOWN_IN.0x0C
        - ARROW_DOWN_OUT.0x0D
        - THINKING_IN.0x0E
        - THINKING_OUT.0x0F
        - MOTION_8_IN.0x10
        - MOTION_8_OUT.0x11
        - WAVE_IN.0x12
        - WAVE_OUT.0x13
        - ERROR.0x14
        - SUCCESS.0x15
        - BOX.0x16
        - LOADING_BAR.0x17
        - ZIP.0x17
        - ZIP_2_TALKING.0x18
        - EMERGENCY.0x20
        - MIDDLE_FINGER.0x1B
        - STROKE.0x1C
        - FULLY_CHARGED.0x1D
        - CHARGING.0x1E
        - HEART.0x21
        - CAKE.0xFE

      behavior:
        startup: "HEART:10" ## name:repetition
        shutdown: "WAVE_OUT:10"
        emergency: "EMERGENCY:1"
        recovery: "SUCCESS:1"

    chest:
      id: 67
      can_id: 0x103
      recognizer: 0x43
      animation:
        - OFF.0x00
        - ON.0x01
        - MOTION_1.0x02
        - MOTION_2.0x03
        - MOTION_6.0x04
        - MOTION_6_0.0x05
        - MOTION_6_1.0x06
        - MOTION_6_2.0x07
        - MOTION_6_3.0x08
        - MOTION_6_4.0x09
        - MOTION_6_5.0x0A
        - MOTION_7.0x0B
        - PROGRAMMING.0x0C
        - STANDBY.0x0D

      behavior:
        startup: "MOTION_1:1"
        shutdown: "OFF:1"
        emergency: "ON:1"
        recovery: "OFF:1"